LEAGUES = [
    ("eng.1","Premier League","🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    ("eng.2","Championship","🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    ("eng.3","League One","🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    ("eng.4","League Two","🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    ("esp.1","La Liga","🇪🇸"),
    ("esp.2","Segunda Division","🇪🇸"),
    ("ger.1","Bundesliga","🇩🇪"),
    ("ger.2","2. Bundesliga","🇩🇪"),
    ("ger.3","3. Liga","🇩🇪"),
    ("ita.1","Serie A","🇮🇹"),
    ("ita.2","Serie B","🇮🇹"),
    ("fra.1","Ligue 1","🇫🇷"),
    ("fra.2","Ligue 2","🇫🇷"),
    ("ned.1","Eredivisie","🇳🇱"),
    ("ned.2","Eerste Divisie","🇳🇱"),
    ("por.1","Primeira Liga","🇵🇹"),
    ("por.2","Liga Portugal 2","🇵🇹"),
    ("sco.1","Scottish Premiership","🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
    ("sco.2","Scottish Championship","🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
    ("tur.1","Super Lig","🇹🇷"),
    ("tur.2","TFF First League","🇹🇷"),
    ("bel.1","Belgian Pro League","🇧🇪"),
    ("gre.1","Super League Greece","🇬🇷"),
    ("ukr.1","Ukrainian Premier","🇺🇦"),
    ("den.1","Superligaen","🇩🇰"),
    ("swe.1","Allsvenskan","🇸🇪"),
    ("nor.1","Eliteserien","🇳🇴"),
    ("aut.1","Austrian Bundesliga","🇦🇹"),
    ("aut.2","Austrian First League","🇦🇹"),
    ("sui.1","Swiss Super League","🇨🇭"),
    ("cze.1","Czech First League","🇨🇿"),
    ("pol.1","Ekstraklasa","🇵🇱"),
    ("rou.1","Liga 1 Romania","🇷🇴"),
    ("srb.1","Serbian SuperLiga","🇷🇸"),
    ("hun.1","OTP Bank Liga","🇭🇺"),
    ("bul.1","First Professional League","🇧🇬"),
    ("cro.1","HNL Croatia","🇭🇷"),
    ("svk.1","Fortuna Liga Slovakia","🇸🇰"),
    ("fin.1","Veikkausliiga","🇫🇮"),
    ("isr.1","Israeli Premier","🇮🇱"),
    ("rus.1","Russian Premier","🇷🇺"),
    ("blr.1","Belarus Premier","🇧🇾"),
    ("bih.1","Premier League Bosnia","🇧🇦"),
    ("slo.1","Slovenian PrvaLiga","🇸🇮"),
    ("ltu.1","A Lyga Lithuania","🇱🇹"),
    ("lva.1","Virsliga Latvia","🇱🇻"),
    ("est.1","Meistriliiga Estonia","🇪🇪"),
    ("mlt.1","Premier League Malta","🇲🇹"),
    ("nir.1","NIFL Premiership","🇬🇧"),
    ("irl.1","League of Ireland","🇮🇪"),
    ("isl.1","Urvalsdeild Iceland","🇮🇸"),
    ("mkd.1","First Football League MKD","🇲🇰"),
    ("cyp.1","First Division Cyprus","🇨🇾"),
    ("arm.1","Armenian Premier","🇦🇲"),
    ("geo.1","Erovnuli Liga Georgia","🇬🇪"),
    ("aze.1","Premyer Liqa Azerbaijan","🇦🇿"),
    ("kaz.1","Kazakhstan Premier","🇰🇿"),
    ("mda.1","Moldova National","🇲🇩"),
    ("usa.1","MLS","🇺🇸"),
    ("usa.2","USL Championship","🇺🇸"),
    ("mex.1","Liga MX","🇲🇽"),
    ("mex.2","Liga de Expansion MX","🇲🇽"),
    ("bra.1","Brasileirao Serie A","🇧🇷"),
    ("bra.2","Brasileirao Serie B","🇧🇷"),
    ("arg.1","Primera Division","🇦🇷"),
    ("arg.2","Primera Nacional","🇦🇷"),
    ("col.1","Liga Betplay","🇨🇴"),
    ("chi.1","Primera Division Chile","🇨🇱"),
    ("ecu.1","Liga Pro Ecuador","🇪🇨"),
    ("per.1","Liga 1 Peru","🇵🇪"),
    ("uru.1","Uruguay Primera","🇺🇾"),
    ("par.1","Division Profesional","🇵🇾"),
    ("ven.1","Liga FUTVE","🇻🇪"),
    ("bol.1","Division Profesional Bolivia","🇧🇴"),
    ("can.1","Canadian Premier League","🇨🇦"),
    ("pan.1","LPF Panama","🇵🇦"),
    ("cri.1","Primera Division Costa Rica","🇨🇷"),
    ("hon.1","Liga Nacional Honduras","🇭🇳"),
    ("jpn.1","J1 League","🇯🇵"),
    ("jpn.2","J2 League","🇯🇵"),
    ("kor.1","K League 1","🇰🇷"),
    ("kor.2","K League 2","🇰🇷"),
    ("chn.1","Chinese Super League","🇨🇳"),
    ("ind.1","Indian Super League","🇮🇳"),
    ("tha.1","Thai League 1","🇹🇭"),
    ("mys.1","Super League Malaysia","🇲🇾"),
    ("idn.1","Liga 1 Indonesia","🇮🇩"),
    ("sau.1","Saudi Pro League","🇸🇦"),
    ("uae.1","UAE Pro League","🇦🇪"),
    ("qat.1","Qatar Stars League","🇶🇦"),
    ("jor.1","Jordan Pro League","🇯🇴"),
    ("oman.1","Oman Professional League","🇴🇲"),
    ("bhr.1","Bahrain Premier","🇧🇭"),
    ("iqi.1","Iraqi Premier League","🇮🇶"),
    ("irn.1","Persian Gulf Pro League","🇮🇷"),
    ("bgd.1","Bangladesh Premier","🇧🇩"),
    ("aus.1","A-League Men","🇦🇺"),
    ("egy.1","Egyptian Premier","🇪🇬"),
    ("rsa.1","PSL South Africa","🇿🇦"),
    ("mar.1","Botola Pro Morocco","🇲🇦"),
    ("nga.1","NPFL Nigeria","🇳🇬"),
    ("tun.1","Ligue Professionnelle 1 Tunisia","🇹🇳"),
    ("ken.1","Football Kenya Federation Premier","🇰🇪"),
    ("alg.1","Ligue Professionnelle 1 Algeria","🇩🇿"),
    ("gha.1","Ghana Premier League","🇬🇭"),
    ("uefa.champions","Champions League","🏆"),
    ("uefa.europa","Europa League","🟠"),
    ("uefa.europaconference","Conference League","🟢"),
    ("conmebol.libertadores","Copa Libertadores","🏆"),
    ("concacaf.champions","CONCACAF Champions","🌎"),
    ("afc.champions","AFC Champions League","🏆"),
    ("caf.champions","CAF Champions League","🏆"),
]

PRIORITY_LEAGUES = [
    "eng.1","esp.1","ger.1","ita.1","fra.1",
    "ned.1","por.1","bel.1","sco.1","tur.1",
    "usa.1","mex.1","bra.1","arg.1",
    "uefa.champions","uefa.europa",
    "kor.1","jpn.1","sau.1",
]

# ── Gate thresholds (calibrated to formula output range) ────────────────────
# Confidence formula is poisson-anchored; outputs ~48-96% on real data.
# ELITE tier requires >= elite_gate. STRONG tier requires >= gate.
HT_BET_TYPES = {
    "HT_OVER_05": {
        "label": "HT Over 0.5 Goals",
        "line": 0.5,
        "gate": 67.0,
        "elite_gate": 85.0,
        "description": "At least 1 goal in first half",
    },
    "HT_OVER_15": {
        "label": "HT Over 1.5 Goals",
        "line": 1.5,
        "gate": 45.0,
        "elite_gate": 72.0,
        "description": "At least 2 goals in first half",
    },
}

ESPN_BASE   = "https://site.api.espn.com/apis/site/v2/sports/soccer"
SOFA_BASE   = "https://api.sofascore.com/api/v1"
TSDB_BASE   = "https://www.thesportsdb.com/api/v1/json/3"
FTDATA_BASE = "https://api.football-data.org/v4"

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1",
]

# Pre-match scan window (minutes before kickoff)
SCAN_WINDOW_MIN = 10    # include games kicking off in >= 10 min
SCAN_WINDOW_MAX = 1440  # look up to 24 hours ahead

VERSION   = "6.1"
APP_TITLE = "ZEUS v6.1"
